{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace : {{ .Values.namespaceDeploy }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "services", "configmaps", "secrets", "serviceaccounts"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace : {{ .Values.namespaceDeploy }}
{{- end -}}
